src/NorthwindWebsite/Presentation/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NorthwindWebsite.Core.Utils;
using NorthwindWebsite.Infrastructure.Entities;

namespace NorthwindWebsite.Presentation.Controllers;

[Authorize(Roles = RolesConstants.Admin)]
public class AdminController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;

    public AdminController(UserManager<ApplicationUser> userManager)
    {
        _userManager = userManager;
    }

    public IActionResult Index() => View();

    public IActionResult Users() 
    {
        var users = _userManager.Users.ToList();

        return View(users);
    }
}

src/NorthwindWebsite/Presentation/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using NorthwindWebsite.Business.Models;
using NorthwindWebsite.Core.Constants;
using NorthwindWebsite.Services.Interfaces;

namespace NorthwindWebsite.Controllers;

public class CategoriesController : Controller
{
    private readonly ICategoryService _categoryService;

    public CategoriesController(
        ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    public async Task<IActionResult> Index()
    {
        var categoriesList = await _categoryService.GetAll();

        var categories = categoriesList.ToList();

        return View("Index", categories);
    }

    [HttpGet]
    public async Task<IActionResult> ImageUpload(int id)
    {
        var fileUploadModel = await _categoryService.GetFileUploadModel(id);

        return View("Upload", fileUploadModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ImageUpload(FileUploadDto fileUploadModel)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError(string.Empty, "Please select a file.");

            return View("Upload", fileUploadModel);
        }

        await _categoryService.UpdateCategoryWithPicture(fileUploadModel);

        return RedirectToAction("Index", "Categories");
    }

    public async Task<IActionResult> Images(int id)
    {
        var imageByteArray = await _categoryService.GetImage(id);

        if (imageByteArray == null)
        {
            return NotFound();
        }

        return File(imageByteArray, HttpContentConstants.ImageBmp);
    }

    public IActionResult BackToCategories() =>
        RedirectToAction("Index");
}

src/NorthwindWebsite/Presentation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace NorthwindWebsite.Presentation.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View("Index");
    }

    public IActionResult Privacy()
    {
        return View("Privacy");
    }
}

src/NorthwindWebsite/Presentation/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using NorthwindWebsite.Business.Models;
using NorthwindWebsite.Business.Services.Interfaces;
using NorthwindWebsite.Entities;
using NorthwindWebsite.Services.Interfaces;

namespace NorthwindWebsite.Presentation.Controllers;

public class ProductsController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly ISupplierService _supplierService;

    public ProductsController(
        IProductService productService,
        ICategoryService categoryService,
        ISupplierService supplierService)
    {
        _productService = productService;
        _categoryService = categoryService;
        _supplierService = supplierService;
    }

    public async Task<IActionResult> Index()
    {
        var products = await _productService.GetProducts();

        return View("Index", products);
    }

    [HttpGet]
    public async Task<IActionResult> Handle(int id)
    {
        var productToCreateOrUpdate = await _productService.GetProductModel(id);

        return View("CreateOrUpdate", productToCreateOrUpdate);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductHandleDto productToCreateOrUpdate)
    {
        productToCreateOrUpdate.CategoryOptions = await _categoryService.GetCategoryOptions();
        productToCreateOrUpdate.SupplierOptions = await _supplierService.GetSupplierOptions();

        if (ModelState.GetFieldValidationState(nameof(Product)) == ModelValidationState.Invalid)
        {
            return View("CreateOrUpdate", productToCreateOrUpdate);
        }

        await _productService.Create(productToCreateOrUpdate.Product);

        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(ProductHandleDto productToCreateOrUpdate)
    {
        productToCreateOrUpdate.CategoryOptions = await _categoryService.GetCategoryOptions();
        productToCreateOrUpdate.SupplierOptions = await _supplierService.GetSupplierOptions();

        if (ModelState.GetFieldValidationState(nameof(Product)) == ModelValidationState.Invalid)
        {
            return View("CreateOrUpdate", productToCreateOrUpdate);
        }

        await _productService.Update(productToCreateOrUpdate.Product);

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _productService.Delete(id);

        return RedirectToAction("Index");
    }

    [ActionName("BackToProducts")]
    public IActionResult BackToMain() => RedirectToAction("Index");
}

src/NorthwindWebsite/Presentation/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NorthwindWebsite.Business.Models;
using NorthwindWebsite.Core.Utils;
using NorthwindWebsite.Infrastructure.Entities;

namespace NorthwindWebsite.Presentation.Controllers;

[Authorize(Roles = RolesConstants.Admin)]
public class RolesController : Controller
{
    private readonly RoleManager<IdentityRole> _roleManager;

    private readonly UserManager<ApplicationUser> _userManager;

    public RolesController(
    RoleManager<IdentityRole> roleManager,
    UserManager<ApplicationUser> userManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var roles = _roleManager.Roles.ToList();

        return View(roles);
    }

    public IActionResult Create() => View();

    [HttpPost]
    public async Task<IActionResult> Create(string name)
    {
        if (!string.IsNullOrEmpty(name))
        {
            var result = await _roleManager.CreateAsync(new IdentityRole(name));

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        return View(name);
    }

    public async Task<IActionResult> Delete(string id)
    {
        var role = await _roleManager.FindByIdAsync(id);

        if (role != null)
        {
            await _roleManager.DeleteAsync(role);
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);

        if (user == null)
        {
            return NotFound();
        }

        var userRoles = await _userManager.GetRolesAsync(user);

        var allRoles = _roleManager.Roles.ToList();

        var model = new ChangeRoleModel
        {
            UserId = user.Id,
            UserEmail = user.Email,
            UserRoles = userRoles,
            AllRoles = allRoles
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(string userId, List<string> roles)
    {
        var user = await _userManager.FindByIdAsync(userId);

        if (user == null)
        {
            return NotFound();
        }

        var userRoles = await _userManager.GetRolesAsync(user);

        var addedRoles = roles.Except(userRoles);

        var removedRoles = userRoles.Except(roles);

        await _userManager.AddToRolesAsync(user, addedRoles);

        await _userManager.RemoveFromRolesAsync(user, removedRoles);

        return RedirectToAction(nameof(Index));
    }
}

src/NorthwindWebsite/Presentation/Views/Admin/Index.cshtml
<h1>Admin section</h1>

<table>
    <tr>
        <td><a asp-controller="Admin" asp-action="Users">List of users</a></td>
    </tr>
    <tr>
        <td>
            <a asp-area="" asp-controller="Roles" asp-action="Index">Roles management</a>
        </td>
    </tr>
</table>

src/NorthwindWebsite/Presentation/Views/Admin/Users.cshtml
@using NorthwindWebsite.Infrastructure.Entities
@model IEnumerable<ApplicationUser>

<h2>List of users</h2>
<table class="table">
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>
                <a class="btn btn-sm btn-primary" asp-controller="Roles" asp-action="Edit" asp-route-userid="@user.Id">Access rights</a>
            </td>
        </tr>
    }
</table>

src/NorthwindWebsite/Presentation/Views/Categories/FromApi.cshtml
<h1>Categories from API</h1>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<link rel="stylesheet" href="~/css/categories-from-api.css" />

<div>
    <ul id="categories" />
</div>

<script>
    let $categoriesList = $('#categories');
    let apiUrl = '../api/categories/';
    let method = 'GET';

    $(function(){
        $.ajax({
        type: method,
        url: apiUrl,
        success: function(categories) {
           $.each(categories, function(i, category){
                $categoriesList.append('<li class="list-item">' + category.categoryName);
                });
            }
        });
    });
</script>

src/NorthwindWebsite/Presentation/Views/Categories/Index.cshtml
@using NorthwindWebsite.Business.Models
@using NorthwindWebsite.Infrastructure.Entities
@using NorthwindWebsite.Presentation.HtmlHelpers
@addTagHelper *, NorthwindWebsite

@model List<Category>

@{
    ViewData["Title"] = "Categories";
}

<link rel="stylesheet" href="~/css//website-css-bundle.css" />

<div class="text-center">
    <h1 class="categories-header">Categories</h1>
</div>

@{
    //Table parameters:
    var widthToHeightRatio = 1.5;
    var imageWidth = 270;
    var imageHeight = imageWidth / widthToHeightRatio;
    var imageType = "image/bmp";

    var collectionMiddle = (int)Math.Round((double)Model.Count / 2);
    var firstRowCategories = Model.Take(collectionMiddle).ToList();
    var secondRowCategories = Model.Skip(collectionMiddle).ToList();
}

<div>
    <table class="d-flex justify-content-center">
        <tr>
            @foreach (var category in firstRowCategories)
            {
                <td>
                    <northwind-image id="@category.CategoryId" text="Image for category @category.CategoryId">
                        @Html.NorthwindImageLink(@category.CategoryId, @imageWidth, @imageHeight, @imageType)
                    </northwind-image>
                </td>
            }
        <tr class="text-center">
                @foreach (var category in firstRowCategories)
                {
                <td class="category-name"><h4>@category.CategoryName</h4></td>
                }
        </tr>
    </table>
    <table class="d-flex justify-content-center">
        <tr>
            @foreach (var category in secondRowCategories)
            {
                <td>
                    <northwind-image id="@category.CategoryId" text="Image for category @category.CategoryId">
                        @Html.NorthwindImageLink(@category.CategoryId, @imageWidth, @imageHeight, @imageType)
                    </northwind-image>
                </td>
            }
        </tr>
        <tr class="text-center">
            @foreach (var category in secondRowCategories)
            {
                <td class="category-name"><h4>@category.CategoryName</h4></td>
            }
        </tr>
    </table>
</div>

@section customFooter
    {
    <footer id="footer" class="border-top footer text-muted d-flex justify-content-center">
        <div class="container">
            <table class="list-group-horizontal">
                <tr>
                    <td class="col-5 ">
                        &copy; 2021 - Northwind Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </td>
                    <td class="col-5">
                        <div class="text-danger font-weight-bolder">Warning! User categories cannot be added.</div>
                    </td>
                </tr>
            </table>
        </div>
    </footer>
}

src/NorthwindWebsite/Presentation/Views/Categories/Upload.cshtml
@using NorthwindWebsite.Business.Models
@model FileUploadDto

@{
    ViewData["Title"] = "Image Upload";
}

<h1>Upload Image</h1>
<h6>(please use .jpg, .jpeg, .bmp, .png files)</h6>

<br>

@using (Html.BeginForm("ImageUpload", "Categories", FormMethod.Post,
new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.CategoryId)
    @Html.ValidationMessageFor(m => m.FileUpload, string.Empty, new { @class = "text-danger" })
    @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })

    <div class="form-horizontal">
        <div class="form-area">
            <div class="form-group">
                <div class="row">
                    <div class="col-5">
                        @Html.LabelFor(x => x.FileUpload, new { @class = "form-label"})
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-5">
                        @Html.TextBoxFor(m => m.FileUpload, new { type = "file", @class = "form-control-file" })
                    </div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="row">
                    <div class="col-5">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<br>

<div>
    <h6>
        @Html.ActionLink("Back to Categories", "BackToCategories", "Categories")
    </h6>
</div>

src/NorthwindWebsite/Presentation/Views/Home/Index.cshtml
@{
    Layout = "_HomepageLayout";
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is created for .NET WEB Mentoring Program at Epam Solutions.</p>
    <p>
        This is a non-commercial training project for Epam. This application is built using Northwind test database.
        The project involves exploring ASP.NET, ASP.NET Core MVC, Controllers, Applications, Requests, RazorPages, Web API, Security, Hosting and Deploy.
    </p>
    <p>
        Disclaimer: All pictures and other materials are used for demonstration purposes only and are not intended for any commercial purpose.
    </p>
</div>

src/NorthwindWebsite/Presentation/Views/Home/_HomepageLayout.cshtml
<!DOCTYPE html>
<html lang="en">

@{
    const string headerSectionName = "Header";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/website-css-bundle.css" asp-append-version="true">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        @if (IsSectionDefined(@headerSectionName))
        {
            @RenderSection(@headerSectionName)
        }
        else
        {
            <nav class="navbar navbar-dark fixed-top">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Northwind</a>
                    <div class="identity-options">
                        <partial name="_LoginPartial">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <!--- spans are used for css to create hamburger lines --->
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>
    <center class="align-content-center">
        <img class="header-image img-fluid" src="~/images/groceries-header.png">
    </center>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/NorthwindWebsite/Presentation/Views/Products/CreateOrUpdate.cshtml
@using NorthwindWebsite.Business.Models
@using NorthwindWebsite.Core.Constants
@using NorthwindWebsite.Entities
@using NorthwindWebsite.Infrastructure.Entities

@model ProductHandleDto

<link rel="stylesheet" href="~/css/website-css-bundle.css" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    @{
    const bool ExcludePropertyErrors = true;

    const string AddNewProductTitle = "Add new product";

    string title = GetTitle();

    ViewData["Title"] = title;

    string postAction = GetPostActionName();

    string GetTitle() => @Model.Product.ProductName == default
                                                    ? AddNewProductTitle
                                                    : $"Edit Product '{@Model.Product.ProductName}'";

    string GetPostActionName() => @Model.Product.ProductId == default
                                                            ? "Create"
                                                            : "Update";
}

<h1>@title</h1>

<br />
<br />

@using (Html.BeginForm(@postAction, "Products"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(product => product.Product.ProductId)
    @Html.ValidationSummary(@ExcludePropertyErrors, string.Empty, new { @class = "text-danger" })

    <div class="form-horizontal">
        <div class="form-area">
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.ProductName, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.ProductName, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.ProductName, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.Category!.CategoryName, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.DropDownListFor(product => product.Product.CategoryId, new SelectList(Model.CategoryOptions,
                    "Key", "Value"), "Select Category", new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.CategoryId, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class=row>
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.Supplier!.CompanyName, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.DropDownListFor(product => product.Product.SupplierId, new SelectList(Model.SupplierOptions,
                    "Key", "Value"), "Select Supplier", new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.SupplierId, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.QuantityPerUnit, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.QuantityPerUnit, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.QuantityPerUnit, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.UnitPrice, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.UnitPrice, NumberFormats.Decimal, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.UnitPrice, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.UnitsInStock, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.UnitsInStock, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.UnitsInStock, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.UnitsOnOrder, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.UnitsOnOrder, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.UnitsOnOrder, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.ReorderLevel, new { @class="form-label"})
                    </div>
                    <div class="col-7">
                        @Html.TextBoxFor(product => product.Product.ReorderLevel, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.ReorderLevel, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="custom-checkbox">
                <div class="row">
                    <div class="col-2">
                        @Html.LabelFor(product => product.Product.Discontinued, new { @class="form-label"})
                    </div>
                    <div class="col-2">
                        @Html.CheckBoxFor(product => product.Product.Discontinued, new { @class="form-control" })
                        @Html.ValidationMessageFor(product => product.Product.Discontinued, string.Empty, htmlAttributes: new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="class=" col-sm-offset-2 col-sm-10">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<br>

<div>
    <h6>
        @Html.ActionLink("Back to Products", "BackToProducts", "Products")
    </h6>
</div>

src/NorthwindWebsite/Presentation/Views/Roles/Create.cshtml
@model string

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">New role</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

src/NorthwindWebsite/Presentation/Views/Roles/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@using NorthwindWebsite.Business.Models

@model ChangeRoleModel

<h2>Assigning roles to user @Model.UserEmail</h2>

<form asp-controller="Roles" asp-action="Edit" method="post">
    <input type="hidden" name="userId" value="@Model.UserId" />
    <div class="form-group">
        @foreach (IdentityRole role in Model.AllRoles)
        {
            <input type="checkbox" name="roles" value="@role.Name"
               @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />

            @role.Name <br />
        }
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

src/NorthwindWebsite/Presentation/Views/Roles/Index.cshtml
@using Microsoft.AspNetCore.Identity

@model IEnumerable<IdentityRole>

<h2>List of roles</h2>
<table class="table">
    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Name</td>
            <td>
                <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<a asp-action="Create">Add role</a>
<br>
<a asp-controller="Admin" asp-action="Users">List of users</a>

src/NorthwindWebsite/Presentation/Views/Shared/Components/Breadcrumbs/_Breadcrumbs.cshtml
@model string

<span>
    @Model
</span>

src/NorthwindWebsite/Presentation/Views/Shared/Components/Breadcrumps/_Breadcrumps.cshtml
@using System.Text

@model StringBuilder

<div>
    @Model
</div>

src/NorthwindWebsite/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@{
    const string headerSectionName = "Header";
    const string customFooterName = "customFooter";
    const string breadcrumbsName = "Breadcrumbs";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        @if (IsSectionDefined(@headerSectionName))
        {
            @RenderSection(@headerSectionName)
        }
        else
        {
            <nav class="navbar navbar-dark fixed-top">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Northwind</a>
                    <div class="identity-options">
                        <partial name="_LoginPartial">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <!--- spans are used for css to create hamburger lines --->
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @await Component.InvokeAsync(@breadcrumbsName)
            @RenderBody()
        </main>
    </div>

    @if (IsSectionDefined(@customFooterName))
    {
        @RenderSection(@customFooterName)
    }
    else
    {
        <footer id="footer" class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - Northwind Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>